name: lenovoctrl
version: 'git'
license: GPL-3.0+
title: Lenovoctrl
summary: Linux daemon and tools to control aspects of Lenovo IdeaPad/Legion devices.
description: |
  Linux daemon and tools to control aspects of Lenovo IdeaPad/Legion devices.
  Currently supports toggling Battery Conservation Mode.

base: core22
grade: devel
compression: lzo
confinement: strict

parts:
  lenovoctrl:
    plugin: go
    source: .
    source-type: local
    build-snaps:
      - go
    go-buildtags:
      - legacy_appindicator
    build-packages:
      - gcc
      - libappindicator3-dev
    stage-packages:
      - libappindicator3-1
      - libatk-bridge2.0-0
      - libatk1.0-0
      - libatspi2.0-0
      - libcairo-gobject2
      - libcairo2
      - libdatrie1
      - libdbusmenu-glib4
      - libdbusmenu-gtk3-4
      - libepoxy0
      - libfontconfig1
      - libfreetype6
      - libfribidi0
      - libgdk-pixbuf2.0-0
      - libgraphite2-3
      - libgtk-3-0
      - libharfbuzz0b
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpixman-1-0
      - libpng16-16
      - libthai0
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libx11-6
      - libxau6
      - libxcb-render0
      - libxcb-shm0
      - libxcb1
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libxdmcp6
      - libxext6
      - libxfixes3
      - libxi6
      - libxinerama1
      - libxkbcommon0
      - libxrandr2
      - libxrender1

apps:
  lenovoctrl:
    command: bin/lenovoctrl
    daemon: simple
    plugs:
      - sysfs-access
      - dbus-daemon-access
    slots:
      - dbus-daemon

plugs:
  sysfs-access:
    interface: system-files
    read: [/sys]
    write: [/sys]
  dbus-daemon-access:
    interface: dbus
    bus: system
    name: com.retrixe.LenovoCtrl.v0

slots:
  dbus-daemon:
    interface: dbus
    bus: system
    name: com.retrixe.LenovoCtrl.v0
