name: lenovoctrl
version: 'git'
license: GPL-3.0+
title: Lenovoctrl
icon: snap/gui/icon.png
summary: Linux daemon and tools to control aspects of Lenovo IdeaPad/Legion devices.
description: |
  Linux daemon and tools to control aspects of Lenovo IdeaPad/Legion devices.
  Currently supports toggling Battery Conservation Mode.
issues: https://github.com/retrixe/lenovoctrl/issues
contact: https://github.com/retrixe/lenovoctrl/issues
website: https://github.com/retrixe/lenovoctrl
source-code: https://github.com/retrixe/lenovoctrl
donation: https://github.com/sponsors/retrixe

base: core22
grade: devel
compression: lzo
confinement: strict # TODO: use classic?

parts:
  lenovoctrl:
    plugin: go
    source: .
    source-type: local
    build-snaps:
      - go
#    go-buildtags:
#      - legacy_appindicator
#    build-packages:
#      - gcc
#      - libappindicator3-dev

apps:
  lenovoctrl:
    command: bin/lenovoctrl
    extensions: [gnome]
    plugs:
      - dbus-daemon-access
  daemon: # lenovoctrl.daemon
    command: bin/lenovoctrl --daemon
    extensions: [gnome]
    daemon: simple
    plugs:
      - sysfs-access
    slots:
      - dbus-daemon

plugs:
  sysfs-access:
    interface: system-files
    read: [/sys]
    write: [/sys]
  dbus-daemon-access:
    interface: dbus
    bus: system
    name: com.retrixe.LenovoCtrl.v0

slots:
  dbus-daemon:
    interface: dbus
    bus: system
    name: com.retrixe.LenovoCtrl.v0
