name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Set up Go >=1.19
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.19.0'
        cache: true
      id: go

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        sudo apt-get install gcc libgtk-3-dev libappindicator3-dev

    - name: Build
      run: ./scripts/build.sh

    - name: Test
      run: ./scripts/test.sh -v
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      if: ${{ success() }}
      with:
        name: lenovoctrl
        path: lenovoctrl

  build-snap:
    name: Build snap
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - uses: snapcore/action-build@v1
      name: Build snap
      id: snapcraft

    - uses: actions/upload-artifact@v3
      name: Upload snap as build artifact
      with:
        name: snap
        path: ${{ steps.snapcraft.outputs.snap }}
